language: ruby
sudo: false
rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
gemfile:
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
matrix:
  exclude:
    # Rails 5 or later requires Ruby 2.2.0 or newer.
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.0.gemfile
before_script:
  - RAILS_ENV=test bundle exec rake db:setup
