language: ruby
sudo: false
services:
  - mysql
rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
before_install:
  - "[[ $BUNDLE_GEMFILE =~ rails_4\\.2 ]] && gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true"
  - "[[ $BUNDLE_GEMFILE =~ rails_4\\.2 ]] && gem install bundler -v '< 2' || true"
before_script:
  - RAILS_ENV=test bundle exec rake db:setup
matrix:
  fast_finish: false
  exclude:
    - rvm: 2.4.9
      gemfile: gemfiles/6.0.gemfile
